version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - CHOWN_FILES=true  # Permet de changer les propriétaires des fichiers

    volumes:
      - ./data:/files:ro
    user: "1000:1000"  # Correspond à l'utilisateur du conteneur
    networks:
      - cashflow-network

  document-processor:
    build: ./services/document-processor
    env_file: .env
    ports:
      - "8001:8080"
    networks:
      - cashflow-network

  transaction-analyzer:
    build: ./services/transaction-analyzer
    env_file: .env
    ports:
      - "8002:8080"
    networks:
      - cashflow-network

networks:
  cashflow-network:
    driver: bridge