version: '3.8'

services:
  document-processor:
    build: ./services/document-processor
    env_file: .env
    ports:
      - "8081:8080"

  transaction-analyzer:
    build: ./services/transaction-analyzer
    env_file: .env
    ports:
      - "8082:8080"

  data-manager:
    build: ./services/data-manager
    env_file: .env
    ports:
      - "8083:8080"
