# Configuration globale du service d'orchestration

# Configuration des workflows
workflow:
  max_retries: 3
  retry_delay: 60
  batch_size: 50
  timeout: 300

# Dossiers de sortie
output_folders:
  workflows: "output/workflows"
  logs: "output/logs"
  temp: "output/temp"
  cache: "output/cache"

# Configuration des services
services:
  document_processor:
    url: "http://document-processor:8080"
    endpoints:
      process: "/api/v1/pdf_processor/process"
      health: "/"

  transaction_analyzer:
    url: "http://localhost:8000"
    endpoints:
      analyze: "/api/v1/transactions/analyze"
      health: "/"